import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
plt.switch_backend('Agg')

# Paths to the CSV files generated by the other modules
hw_path = "../alex_holt_winters/rezultate_holt_winters.csv"
sarima_path = "../sarima_analysis/rezultate/erori_sarima_2024.csv"

print("--- Cerinta 6: Compararea Metodelor Univariate de Prognoza ---")

# Incarcare date erori
try:
    df_hw = pd.read_csv(hw_path)
    df_sarima = pd.read_csv(sarima_path)
except Exception as e:
    print("Eroare la incarcarea fisierelor CSV. Asigurati-va ca ati rulat modulele anterioare.")
    print(e)
    exit(1)

# Formatare SARIMA pentru a avea doar 4 zecimale, cum e HW
df_sarima['MAE'] = df_sarima['MAE'].round(4)
df_sarima['RMSE'] = df_sarima['RMSE'].round(4)
df_sarima['MAPE'] = df_sarima['MAPE'].round(4)

# Concatenare
df_comparatie = pd.concat([df_hw, df_sarima], ignore_index=True)

# Sortare dupa RMSE (cel mai bun model primul)
df_comparatie = df_comparatie.sort_values(by="RMSE", ascending=True).reset_index(drop=True)

print("\nTabel Comparativ Acuratete Prognoze (Set de Test 2024-2025):")
print(df_comparatie.to_string())

# Salvare CSV combinat
df_comparatie.to_csv("tabel_comparatie_erori.csv", index=False)

# Creare grafic cu bare (Bar chart) pentru vizualizarea erorilor
labels = df_comparatie['Model'].tolist()
mae_vals = df_comparatie['MAE'].tolist()
rmse_vals = df_comparatie['RMSE'].tolist()

x = np.arange(len(labels))  # label locations
width = 0.35  # width of the bars

fig, ax = plt.subplots(figsize=(12, 6))
rects1 = ax.bar(x - width/2, mae_vals, width, label='MAE (Eroarea Medie Absoluta)', color='skyblue')
rects2 = ax.bar(x + width/2, rmse_vals, width, label='RMSE (Radacina Erorii Medii Pătratice)', color='salmon')

# Adaugare etichete, titlu etc.
ax.set_ylabel('Valoarea Erorii')
ax.set_title('Compararea Acuratetei Metodelor de Prognoza Univariata (Orizont 2024-2025)')
ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=15, ha="right")
ax.legend()

# Adaugare numere pe bare
def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.4f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=9)

autolabel(rects1)
autolabel(rects2)

plt.grid(axis='y', alpha=0.3)
plt.tight_layout()

# Salvare grafic
plt.savefig("grafic_comparatie_modele.png", dpi=300)
print("\nGraficul de comparatie a fost salvat ca 'grafic_comparatie_modele.png'.")
print("Tabelul de comparatie a fost salvat ca 'tabel_comparatie_erori.csv'.")
